// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	model "github.com/pthum/stripcontrol-golang/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// EventHandler is an autogenerated mock type for the EventHandler type
type EventHandler struct {
	mock.Mock
}

type EventHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *EventHandler) EXPECT() *EventHandler_Expecter {
	return &EventHandler_Expecter{mock: &_m.Mock}
}

// PublishProfileEvent provides a mock function with given fields: event
func (_m *EventHandler) PublishProfileEvent(event *model.ProfileEvent) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.ProfileEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventHandler_PublishProfileEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishProfileEvent'
type EventHandler_PublishProfileEvent_Call struct {
	*mock.Call
}

// PublishProfileEvent is a helper method to define mock.On call
//   - event *model.ProfileEvent
func (_e *EventHandler_Expecter) PublishProfileEvent(event interface{}) *EventHandler_PublishProfileEvent_Call {
	return &EventHandler_PublishProfileEvent_Call{Call: _e.mock.On("PublishProfileEvent", event)}
}

func (_c *EventHandler_PublishProfileEvent_Call) Run(run func(event *model.ProfileEvent)) *EventHandler_PublishProfileEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.ProfileEvent))
	})
	return _c
}

func (_c *EventHandler_PublishProfileEvent_Call) Return(_a0 error) *EventHandler_PublishProfileEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventHandler_PublishProfileEvent_Call) RunAndReturn(run func(*model.ProfileEvent) error) *EventHandler_PublishProfileEvent_Call {
	_c.Call.Return(run)
	return _c
}

// PublishStripEvent provides a mock function with given fields: event
func (_m *EventHandler) PublishStripEvent(event *model.StripEvent) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.StripEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventHandler_PublishStripEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishStripEvent'
type EventHandler_PublishStripEvent_Call struct {
	*mock.Call
}

// PublishStripEvent is a helper method to define mock.On call
//   - event *model.StripEvent
func (_e *EventHandler_Expecter) PublishStripEvent(event interface{}) *EventHandler_PublishStripEvent_Call {
	return &EventHandler_PublishStripEvent_Call{Call: _e.mock.On("PublishStripEvent", event)}
}

func (_c *EventHandler_PublishStripEvent_Call) Run(run func(event *model.StripEvent)) *EventHandler_PublishStripEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.StripEvent))
	})
	return _c
}

func (_c *EventHandler_PublishStripEvent_Call) Return(_a0 error) *EventHandler_PublishStripEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventHandler_PublishStripEvent_Call) RunAndReturn(run func(*model.StripEvent) error) *EventHandler_PublishStripEvent_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields:
func (_m *EventHandler) Shutdown() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventHandler_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type EventHandler_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *EventHandler_Expecter) Shutdown() *EventHandler_Shutdown_Call {
	return &EventHandler_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *EventHandler_Shutdown_Call) Run(run func()) *EventHandler_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *EventHandler_Shutdown_Call) Return(_a0 error) *EventHandler_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventHandler_Shutdown_Call) RunAndReturn(run func() error) *EventHandler_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventHandler creates a new instance of EventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventHandler {
	mock := &EventHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
