server:
    port: 8080
    mode: debug
database:
    user: postgres
    pass: changeme
    host: localhost
    port: 5432
    name: stripcontrol
messaging:
    host: localhost
    port: 1883
    striptopic: ledstrip
    profiletopic: profile
