server:
    port: 8080
    mode: debug
database:
    type: sqlite
    user: sa
    pass: password
    host: stripcontrol.sqlite
    port: 5432
    name: stripcontrol
messaging:
    host: localhost
    port: 1883
    striptopic: ledstrip
    profiletopic: profile
    disabled: true
