server:
    port: 8080
    mode: debug
database:
    type: sqlite
    user: sa
    pass: password
    host: stripcontroldev.sqlite
    port: 5432
    name: stripcontrol
messaging:
    host: localhost
    port: 1883
    striptopic: ledstrip
    profiletopic: profile
    disabled: true
csv:
    datadir: configs/
    intervalmin: 60

telegram:
    enable: true
    enabledebug: false
    apikey: 123456789:asdf
    allowedusers:
      - 123456789